<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://www.github.com/yigitus/
 * @since      1.0.0
 *
 * @package    Yts_Fab
 * @subpackage Yts_Fab/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Yts_Fab
 * @subpackage Yts_Fab/admin
 * @author     yigitus <zenginyigit@yandex.com>
 */
class Yts_Fab_Admin {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of this plugin.
	 * @param      string    $version    The version of this plugin.
	 */
	public function __construct( $plugin_name, $version ) {

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Yts_Fab_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Yts_Fab_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'css/yts-fab-admin.css', array(), $this->version, 'all' );

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Yts_Fab_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Yts_Fab_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */
		wp_register_script(
			'yts-fab-admin-script',
			plugin_dir_url( __FILE__ ) . 'js/yts-fab-admin.js',
			array( 'jquery' ),
			'1.0  ',
			false
		);
		$saved_attachment_post_id = get_option( 'media_selector_attachment_id', 0 );
		wp_enqueue_script( 'yts-fab-admin-script' );
	}

	/**
 	* Generated by the WordPress Option Page generator
 	* at http://jeremyhixon.com/wp-tools/option-page/
 	*/

	private $yts_fab_options;

	public function yts_add_plugin_page() {
		add_theme_page(
			'YTS Floating action button', // page_title
			'YTS Floating action button', // menu_title
			'manage_options', // capability
			'yts-fab', // menu_slug
			array( $this, 'yts_create_admin_page' ) // function
		);
	}

	public function yts_create_admin_page() {
		$this->yts_fab_options = get_option( 'yts_fab_option_name' ); ?>

		<div class="wrap">
			<h2>YTS Floating action button</h2>
			<p>Customize FAB</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'yts_fab_option_group' );
					do_settings_sections( 'yts-fab-admin' );
					submit_button();
					do_settings_sections( 'yts_fab_advanced_setting_section' );
				?>
			</form>
		</div>
	<?php }

	public function yts_page_init() {
		register_setting(
			'yts_fab_option_group', // option_group
			'yts_fab_option_name', // option_name
			array( $this, 'yts_fab_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'yts_fab_setting_section', // id
			'Settings', // title
			array( $this, 'yts_fab_section_info' ), // callback
			'yts-fab-admin' // page
		);

		add_settings_section(
			'yts_fab_advanced_setting_section', // id
			'Advanced settings', // title
			array( $this, 'yts_fab_section_info' ), // callback
			'yts-fab-admin' // page
		);

		add_settings_field(
			'yaz_0', // id
			'Text', // title
			array( $this, 'yaz_0_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		add_settings_field(
			'konum_1', // id
			'Location', // title
			array( $this, 'konum_1_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		add_settings_field(
			'link_2', // id
			'Link', // title
			array( $this, 'link_2_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		add_settings_field(
			'media_selector_3', // id
			'Image', // title
			array( $this, 'media_selector_3_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		add_settings_field(
			'width_4', // id
			'Width', // title
			array( $this, 'width_4_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		add_settings_field(
			'height_5', // id
			'Height', // title
			array( $this, 'height_5_callback' ), // callback
			'yts-fab-admin', // page
			'yts_fab_setting_section' // section
		);

		//Advanced Settings

		add_settings_field(
			'border_radius_0',
			'Border radius',
			array( $this, 'border_radius_0_callback'),
			'yts-fab-admin',
			'yts_fab_advanced_setting_section'
		);
	}

	public function yts_fab_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['yaz_0'] ) ) {
			$sanitary_values['yaz_0'] = esc_textarea( $input['yaz_0'] );
		}

		if ( isset( $input['konum_1'] ) ) {
			$sanitary_values['konum_1'] = $input['konum_1'];
		}

		if ( isset( $input['link_2'] ) ) {
			$sanitary_values['link_2'] = esc_textarea( $input['link_2'] );
		}

		if ( isset( $input['media_selector_3'] ) ) {
			$sanitary_values['media_selector_3'] = esc_textarea( $input['media_selector_3'] );
		}

		if ( isset( $input['width_4'] ) ) {
			$sanitary_values['width_4'] = esc_textarea( $input['width_4'] );
		}

		if ( isset( $input['height_5'] ) ) {
			$sanitary_values['height_5'] = esc_textarea( $input['height_5'] );
		}

		if ( isset( $input['border_radius_0'] ) ) {
			$sanitary_values['border_radius_0'] = esc_textarea( $input['border_radius_0'] );
		}

		return $sanitary_values;
	}

	public function yts_fab_section_info() {
		
	}

	public function yaz_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="yts_fab_option_name[yaz_0]" id="yaz_0">%s</textarea>',
			isset( $this->yts_fab_options['yaz_0'] ) ? esc_attr( $this->yts_fab_options['yaz_0']) : 'Help'
		);
	}

	public function konum_1_callback() {
		?> <select name="yts_fab_option_name[konum_1]" id="konum_1">
			<?php $selected = (isset( $this->yts_fab_options['konum_1'] ) && $this->yts_fab_options['konum_1'] === 'right') ? 'selected' : '' ; ?>
			<option value="right" <?php echo $selected; ?>>Right</option>
			<?php $selected = (isset( $this->yts_fab_options['konum_1'] ) && $this->yts_fab_options['konum_1'] === 'left') ? 'selected' : '' ; ?>
			<option value="left" <?php echo $selected; ?>>Left</option>
		</select> <?php
	}

	public function link_2_callback() {
		printf(
			'<textarea class="large-text" rows="2" name="yts_fab_option_name[link_2]" id="link_2">%s</textarea>',
			isset( $this->yts_fab_options['link_2'] ) ? esc_attr( $this->yts_fab_options['link_2']) : ''
		);
	}

	
	public function media_selector_3_callback() {
		wp_enqueue_media();
		$image_url;
		$image_id = isset($this->yts_fab_options['media_selector_3']) ? isset($this->yts_fab_options['media_selector_3']) : "";
		?>
        <div class='image-preview-wrapper'>
            <img id='image-preview' src='<?php echo  $image_id != "" && $image_id != NULL && isset($image_id) ? esc_attr( wp_get_attachment_image_src($image_id)[0]) : plugin_dir_url( __FILE__ ) . 'placeholder.png' ; ?>' width='200'>
        </div>
        <input id="upload_image_button" type="button" class="button" value="<?php  _e('Select image', 'yts_fab')  ?>" >
        <input type='hidden' name='yts_fab_option_name[media_selector_3]' value=" <?php echo isset( $this->yts_fab_options['media_selector_3'] ) ? esc_attr( $this->yts_fab_options['media_selector_3'] ) : '' ; ?> " id='media_selector_3'  >
		<?php
	}
	
	
	public function width_4_callback() {
		printf(
			'<input type="text" name="yts_fab_option_name[width_4]" id="width_4" value="%s">',
			isset( $this->yts_fab_options['width_4'] ) ? esc_attr( $this->yts_fab_options['width_4']) : '50'
		);
	}

	public function height_5_callback() {
		printf(
			'<input type="text" name="yts_fab_option_name[height_5]" id="height_5" value="%s">',
			isset( $this->yts_fab_options['height_5'] ) ? esc_attr( $this->yts_fab_options['height_5']) : '50'
		);
	}

	//Advanced settings

	public function border_radius_0_callback() {
		printf(
			'<input type="text" name="yts_fab_option_name[border_radius_0]" id="border_radius_0" value="%s">',
			isset( $this->yts_fab_options['border_radius_0'] ) ? esc_attr( $this->yts_fab_options['border_radius_0']) : '10'
		);
	}

}
